"""add food_log table

Revision ID: 9e1840680b76
Revises: 0ddc8bda2cb1
Create Date: 2026-07-24 00:25:16.714613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1840680b76'
down_revision: Union[str, Sequence[str], None] = '0ddc8bda2cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Numeric(), nullable=False),
    sa.Column('carbs_g', sa.Numeric(), nullable=False),
    sa.Column('fat_g', sa.Numeric(), nullable=False),
    sa.Column('meal_type', sa.String(), nullable=False),
    sa.Column('logged_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_log')
    # ### end Alembic commands ###
