"""add target sets and reps to planned exercises

Revision ID: ea36cd6b9640
Revises: aa7a8c7194cc
Create Date: 2026-07-28 02:01:05.235920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea36cd6b9640'
down_revision: Union[str, Sequence[str], None] = 'aa7a8c7194cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planned_exercises', sa.Column('target_sets', sa.Integer(), nullable=True))
    op.add_column('planned_exercises', sa.Column('target_reps', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planned_exercises', 'target_reps')
    op.drop_column('planned_exercises', 'target_sets')
    # ### end Alembic commands ###
